export const UPDATE_BENEFITS_STATUS_CONFIRMATION_CODE = 'UPDATE_BENEFITS_STATUS_CONFIRMATION_CODE';
export type UPDATE_BENEFITS_STATUS_CONFIRMATION_CODE = typeof UPDATE_BENEFITS_STATUS_CONFIRMATION_CODE;

export const SUBMIT_BENEFITS_STATUS_BEGIN = 'SUBMIT_BENEFITS_STATUS_BEGIN';
export type SUBMIT_BENEFITS_STATUS_BEGIN = typeof SUBMIT_BENEFITS_STATUS_BEGIN;

export const SUBMIT_BENEFITS_STATUS_SUCCESS = 'SUBMIT_BENEFITS_STATUS_SUCCESS';
export type SUBMIT_BENEFITS_STATUS_SUCCESS = typeof SUBMIT_BENEFITS_STATUS_SUCCESS;

export const SUBMIT_BENEFITS_STATUS_ERROR = 'SUBMIT_BENEFITS_STATUS_ERROR';
export type SUBMIT_BENEFITS_STATUS_ERROR = typeof SUBMIT_BENEFITS_STATUS_ERROR;
