export const UPDATE_BENEFITS_FILE_NUMBER = 'UPDATE_BENEFITS_FILE_NUMBER';
export type UPDATE_BENEFITS_FILE_NUMBER = typeof UPDATE_BENEFITS_FILE_NUMBER;

export const UPDATE_BENEFITS_VETERAN_FIRST_NAME = 'UPDATE_BENEFITS_VETERAN_FIRST_NAME';
export type UPDATE_BENEFITS_VETERAN_FIRST_NAME = typeof UPDATE_BENEFITS_VETERAN_FIRST_NAME;

export const UPDATE_BENEFITS_VETERAN_LAST_NAME = 'UPDATE_BENEFITS_VETERAN_LAST_NAME';
export type UPDATE_BENEFITS_VETERAN_LAST_NAME = typeof UPDATE_BENEFITS_VETERAN_LAST_NAME;

export const UPDATE_BENEFITS_ZIP_CODE = 'UPDATE_BENEFITS_ZIP_CODE';
export type UPDATE_BENEFITS_ZIP_CODE = typeof UPDATE_BENEFITS_ZIP_CODE;

export const SUBMIT_BENEFITS_BEGIN = 'SUBMIT_BENEFITS_BEGIN';
export type SUBMIT_BENEFITS_BEGIN = typeof SUBMIT_BENEFITS_BEGIN;

export const SUBMIT_BENEFITS_SUCCESS = 'SUBMIT_BENEFITS_SUCCESS';
export type SUBMIT_BENEFITS_SUCCESS = typeof SUBMIT_BENEFITS_SUCCESS;

export const SUBMIT_BENEFITS_ERROR = 'SUBMIT_BENEFITS_ERROR';
export type SUBMIT_BENEFITS_ERROR = typeof SUBMIT_BENEFITS_ERROR;
